name: CI/CD Pipeline

on: 
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: |
          (Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | python -
          echo "$env:APPDATA\Python\Scripts" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8

      - name: Install Dependencies with Poetry
        run: |
          poetry install
          
      - name: Run black to format the code
        run: |
          poetry run black --line-length 79 --skip-string-normalization --target-version py311 --no-verify .

      - name: Run Linting (flake8)
        run: |
          poetry run flake8 .

      - name: Run Tests (pytest)
        run: |
          poetry run pytest
